// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5q1DPJXrHxzxpnnVzIAhpV3m15rGyW0U',
    appId: '1:274776740897:web:c62a369b1cf6b0d711bf60',
    messagingSenderId: '274776740897',
    projectId: 'demoproject-a01d5',
    authDomain: 'demoproject-a01d5.firebaseapp.com',
    storageBucket: 'demoproject-a01d5.appspot.com',
    measurementId: 'G-1T7V58FESV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDESgwbOxOxlOO5rEf4-kNip_1KzXB6Nyw',
    appId: '1:274776740897:android:b50726b325247b6011bf60',
    messagingSenderId: '274776740897',
    projectId: 'demoproject-a01d5',
    storageBucket: 'demoproject-a01d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEU0glXa00RxAjb90kAW1lnBKxRYmTM9Q',
    appId: '1:274776740897:ios:7ae8fe26e90d051d11bf60',
    messagingSenderId: '274776740897',
    projectId: 'demoproject-a01d5',
    storageBucket: 'demoproject-a01d5.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEU0glXa00RxAjb90kAW1lnBKxRYmTM9Q',
    appId: '1:274776740897:ios:98c67d33c24f567c11bf60',
    messagingSenderId: '274776740897',
    projectId: 'demoproject-a01d5',
    storageBucket: 'demoproject-a01d5.appspot.com',
    iosBundleId: 'com.example.demoApp.RunnerTests',
  );
}
